// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhf2c5M1w_It8_AnG2mlzWicYnBSekXvw',
    appId: '1:219159014153:web:398f111572255d759dc1d8',
    messagingSenderId: '219159014153',
    projectId: 'audio-e0f15',
    authDomain: 'audio-e0f15.firebaseapp.com',
    storageBucket: 'audio-e0f15.appspot.com',
    measurementId: 'G-07CMW6ZWXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_KS1XUgfHkTSQRfpqFFj2eYNSS1dScA',
    appId: '1:219159014153:android:17d150164f3e681d9dc1d8',
    messagingSenderId: '219159014153',
    projectId: 'audio-e0f15',
    storageBucket: 'audio-e0f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYTn7HjxlRBabyIaD13Ep4NHGoP6ldA38',
    appId: '1:219159014153:ios:8fa465eec068c1129dc1d8',
    messagingSenderId: '219159014153',
    projectId: 'audio-e0f15',
    storageBucket: 'audio-e0f15.appspot.com',
    androidClientId: '219159014153-mi9f3d5b1ok6tjlsalsj518cphgujgt1.apps.googleusercontent.com',
    iosClientId: '219159014153-7i0tt86q5hoahas218fkok6p26nmd270.apps.googleusercontent.com',
    iosBundleId: 'com.example.dealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYTn7HjxlRBabyIaD13Ep4NHGoP6ldA38',
    appId: '1:219159014153:ios:0cb99f6cd437a2569dc1d8',
    messagingSenderId: '219159014153',
    projectId: 'audio-e0f15',
    storageBucket: 'audio-e0f15.appspot.com',
    androidClientId: '219159014153-mi9f3d5b1ok6tjlsalsj518cphgujgt1.apps.googleusercontent.com',
    iosClientId: '219159014153-luu2lk47nvsgq3etluj7mvf9su4lpm1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.dealer.RunnerTests',
  );
}
